Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.provision :shell, inline: "sudo echo 'nameserver 208.67.222.222' > /etc/resolv.conf"
	config.vm.network "forwarded_port", guest: 2020, host: 5678
	config.vm.network "forwarded_port", guest: 5432, host: 1234

	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end

	config.vm.synced_folder "web/", "/home/vagrant/web", :mount_options => ["dmode=777", "fmode=777"]
	config.vm.synced_folder "db/", "/home/vagrant/db", :mount_options => ["dmode=777", "fmode=777"]

	# ci mette molto tempo(circa 20 min)
	config.vm.provision "docker" do |d|
		d.build_image "-t=postgres /home/vagrant/db"
		d.build_image "-t=web /home/vagrant/web"
	end

	config.vm.provision "docker", run: "always" do |d|
		d.run "postgres", args: "-p 5432:5432 --name postgres"
		d.run "web", args: "-p 2020:8080 --link postgres:postgres"
	end
end